Booking app/Controllers/HotelController.cs
using AutoMapper;
using Booking_app.Services.Interfaces;
using BookingApp.Models;
using BookingApp.Models.DTOS;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BookingApp.Controllers
{
    public class HotelController : Controller
    {
        private readonly IHotelService _service;
        private readonly IMapper _mapper;
        private readonly IRezervationService _rezervationService;

        public HotelController(IHotelService service, 
            IMapper mapper,
            IRezervationService rezervationService)
        {
            _service = service;
            _mapper = mapper;
            _rezervationService = rezervationService;
        }
        // GET: HotelController
        public ActionResult Index()
        {
            _rezervationService.SetRoomStatus();
            var hotel = _service.FindAll();
            var model = _mapper.Map<List<HotelDTO>, List<HotelVM>>((List<HotelDTO>)hotel);
            return View(model);
        }

        // GET: HotelController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: HotelController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HotelController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HotelVM model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }
                var hotel = _mapper.Map<HotelDTO>(model);

                var isSucces = _service.Create(hotel);
                if (!isSucces)
                {
                    ModelState.AddModelError("", "Something went wrong...");
                    return View(model);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Something went wrong...");
                return View(model);
            }
        }

        // GET: HotelController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: HotelController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HotelController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: HotelController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Booking app/Controllers/RoomController.cs
using AutoMapper;
using Booking_app.Services.Interfaces;
using BookingApp.Models;
using BookingApp.Models.DTOS;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Booking_app.Controllers
{
    public class RoomController : Controller
    {

        private readonly IRoomService _service;
        private readonly IRezervationService _rezervationService;
        private readonly IHotelService _hotelService;
        private readonly IMapper _mapper;

        public RoomController(IRoomService service, IMapper mapper, 
            IRezervationService rezervationService, IHotelService hotelService)
        {
            _service = service;
            _mapper = mapper;
            _rezervationService = rezervationService;
            _hotelService = hotelService;
        }
        // GET: RoomController
        public ActionResult Index()
        {
            _rezervationService.SetRoomStatus();
            var room = _service.FindAll();
            var model = _mapper.Map<List<RoomDTO>, List<RoomVM>>((List<RoomDTO>)room);
            return View(model);
        }

        // GET: RoomController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: RoomController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RoomController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RoomVM model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }
                var room = _mapper.Map<RoomDTO>(model);

                var isSucces = _service.Create(room);
                if (!isSucces)
                {
                    ModelState.AddModelError("", "Something went wrong...");
                    return View(model);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Something went wrong...");
                return View(model);
            }
        }

        // GET: RoomController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: RoomController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: RoomController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: RoomController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Booking app/Controllers/RoomtypeController.cs
using AutoMapper;
using Booking_app.Services.Interfaces;
using BookingApp.Models;
using BookingApp.Models.DTOS;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BookingApp.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class RoomTypeController : Controller
    {
        private readonly IRoomTypeService _service;
        private readonly IRezervationService _rezervationService;
        private readonly IMapper _mapper;

        public RoomTypeController(IRoomTypeService service, IMapper mapper, IRezervationService rezervationService)
        {
            _service = service;
            _mapper = mapper;
            _rezervationService = rezervationService;
        }
        // GET: RoomTypeController
        public ActionResult Index()
        {
            _rezervationService.SetRoomStatus();
            var roomType = _service.FindAll();
            var model = _mapper.Map<List<RoomTypeDTO>, List<RoomTypeVM>>((List<RoomTypeDTO>)roomType);
            return View(model);
        }

        // GET: RoomTypeController/Details/5
        public ActionResult Details(int id)
        {
            if(!_service.isExis(id))
            {
                return NotFound();
            }
            var roomtype = _service.FindById(id);
            var model = _mapper.Map<RoomTypeVM>(roomtype);
            return View(model);
        }

        // GET: RoomTypeController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RoomTypeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RoomTypeVM model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }
                var roomType = _mapper.Map<RoomTypeDTO>(model);

                var isSucces = _service.Create(roomType);
                if (!isSucces)
                {
                    ModelState.AddModelError("", "Something went wrong...");
                    return View(model);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Something went wrong...");
                return View(model);
            }
        }

        // GET: RoomTypeController/Edit/5
        public ActionResult Edit(int id)
        {
            if (!_service.isExis(id)){
                return NotFound();
            }
            var roomType = _service.FindById(id);
            var model = _mapper.Map<RoomTypeVM>(roomType);
            return View(model);
        }

        // POST: RoomTypeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id,RoomTypeVM model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }
                var roomType = _mapper.Map<RoomTypeDTO>(model);
                var isSucces = _service.Update(roomType);
                if (!isSucces)
                {
                    ModelState.AddModelError("", "Something went wrong...");
                    return View(model);
                }
                return RedirectToAction(nameof(Index));
            }
            catch(Microsoft.EntityFrameworkCore.DbUpdateException)
            {
                ModelState.AddModelError("", "The hotel does not exist!");
                return View(model);
            }
            catch
            {
                ModelState.AddModelError("", "Something went wrong...");
                return View(model);
            }
        }

        // GET: RoomTypeController/Delete/5
        public ActionResult Delete(int id)
        {
            if (!_service.isExis(id))
            {
                return NotFound();
            }
            var roomType = _service.FindById(id);
            var model = _mapper.Map<RoomTypeVM>(roomType);
            return View(model);
        }

        // POST: RoomTypeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, RoomTypeVM model)
        {
            try
            {     
                if(model == null)
                {
                    return NotFound();
                }
                var isSucces = _service.Delete(_mapper.Map<RoomTypeDTO>(model));
                if (!isSucces)
                {
                    return View(model);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Something went wrong...");
                return View(model);
            }
        }
    }
}

Booking app/Views/Shared/_Layout.cshtml
@using Booking_app.Data
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookingApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookingApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookingApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        
                        @if (SignInManager.IsSignedIn(User))
                        {
                            if (User.IsInRole("Administrator")) { 
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Hotel" asp-action="Index">Hotels</a>
                                </li> 
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="RoomType" asp-action="Index">RoomTypes</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Room" asp-action="Index">Rooms</a>
                                </li> 
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Rezervation" asp-action="Index">Rezervations</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-dark" href="#" id="dropdown" data-bs-toggle="dropdown" aria-haspopup="true">Users</a>
                                    <div class="dropdown-menu" aria-labelledby="dropdown">
                                        <a class="dropdown-item text-dark" asp-area="" asp-controller="User" asp-action="Index">Simple Users</a>
                                        <a class="dropdown-item text-dark" asp-area="" asp-controller="User" asp-action="ListAdmins">Administrators</a>
                                    </div>
                                </li>
                            }
                            if (User.IsInRole("User"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Rezervation" asp-action="RoomsList">Rooms</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Rezervation" asp-action="UserIndex">Rezervations</a>
                                </li>
                            }
                        }
                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - BookingApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>